# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f1d89d9526d6e4103721aa59adc286f8f2cdb45b2ee21dee87ebc81f02d67fc0ed54564ef25329bd47a7f9f0c33e25c883970bf869576b8a52a20555aeac77b7

test:
  secret_key_base: 3ab4a4ce46e638ccebd3e59a9dd6d8f4ba542446f9eb74da7e66f7377e7ac3af6a625684c8a4a0118e31c4e64e6d3bbb068244d550fe4f73da8f7171e02ff244

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
